name: substrate-python-backend
channels:
  - conda-forge
dependencies:
  - supabase
  - fastapi
  - python
  - uvicorn[standard]
  - boto3
  - pydantic
  # todo fix all dependencies
  - pip
  - pip:
    - human-id
    - pydantic_settings
